application: gm-selector
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)
  static_files: client/\1
  upload: client/(.+)

- url: /
  static_files: client/index.html
  upload: client/index.html

libraries:
- name: webapp2
  version: "2.5.2"
